"""change password fields

Revision ID: 0aea5ffcd66b
Revises: 4311d9bb0ebd
Create Date: 2024-09-04 08:47:38.990360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aea5ffcd66b'
down_revision: Union[str, None] = '4311d9bb0ebd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.LargeBinary(length=60), nullable=False))
    op.add_column('users', sa.Column('password_salt', sa.LargeBinary(length=29), nullable=False))
    op.drop_index('email_pass_idx', table_name='users')
    op.create_index('email_pass_idx', 'users', ['email', 'password_hash', 'password_salt'], unique=False)
    op.drop_index('user_email_pass_idx', table_name='users')
    op.create_index('user_email_pass_idx', 'users', ['username', 'email', 'password_hash', 'password_salt'], unique=False)
    op.drop_index('user_pass_idx', table_name='users')
    op.create_index('user_pass_idx', 'users', ['username', 'password_hash', 'password_salt'], unique=False)
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index('user_pass_idx', table_name='users')
    op.create_index('user_pass_idx', 'users', ['username', 'password'], unique=False)
    op.drop_index('user_email_pass_idx', table_name='users')
    op.create_index('user_email_pass_idx', 'users', ['username', 'email', 'password'], unique=False)
    op.drop_index('email_pass_idx', table_name='users')
    op.create_index('email_pass_idx', 'users', ['email', 'password'], unique=False)
    op.drop_column('users', 'password_salt')
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
