"""create transactions table

Revision ID: 8d3fd47d2faf
Revises: d6fb3c3dd2b3
Create Date: 2024-07-21 01:24:00.681388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d3fd47d2faf'
down_revision: Union[str, None] = 'd6fb3c3dd2b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Float(asdecimal=True), nullable=False),
    sa.Column('type_of_transaction', sa.String(length=20), nullable=False),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index('amount_type_of_transaction_idx', 'transactions', ['amount', 'type_of_transaction'], unique=False)
    op.create_index('desc_amount_idx', 'transactions', ['description', 'amount'], unique=False)
    op.create_index('desc_amount_userid_idx', 'transactions', ['description', 'amount', 'user_id'], unique=False)
    op.create_index('type_of_transaction_date_idx', 'transactions', ['type_of_transaction', 'registration_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('type_of_transaction_date_idx', table_name='transactions')
    op.drop_index('desc_amount_userid_idx', table_name='transactions')
    op.drop_index('desc_amount_idx', table_name='transactions')
    op.drop_index('amount_type_of_transaction_idx', table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
