"""create user table

Revision ID: d6fb3c3dd2b3
Revises: 
Create Date: 2024-07-21 00:58:17.196545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6fb3c3dd2b3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('username', sa.String(), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index('email_created_at_idx', 'users', ['email', 'created_at'], unique=False)
    op.create_index('email_pass_idx', 'users', ['email', 'password'], unique=False)
    op.create_index('email_updated_at_idx', 'users', ['email', 'updated_at'], unique=False)
    op.create_index('user_created_at_idx', 'users', ['username', 'created_at'], unique=False)
    op.create_index('user_email_pass_idx', 'users', ['username', 'email', 'password'], unique=False)
    op.create_index('user_pass_idx', 'users', ['username', 'password'], unique=False)
    op.create_index('user_updated_at_idx', 'users', ['username', 'updated_at'], unique=False)
    op.create_unique_constraint(None, 'users', ['username'])
    op.drop_column('users', 'active')
    op.drop_column('users', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('users', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index('user_updated_at_idx', table_name='users')
    op.drop_index('user_pass_idx', table_name='users')
    op.drop_index('user_email_pass_idx', table_name='users')
    op.drop_index('user_created_at_idx', table_name='users')
    op.drop_index('email_updated_at_idx', table_name='users')
    op.drop_index('email_pass_idx', table_name='users')
    op.drop_index('email_created_at_idx', table_name='users')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'username')
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###
