services:
  web:
    container_name: fintracker-api
    build:
      context: .
      dockerfile: Dockerfile-dev
    command: bash -c 'uvicorn app.main:app --host 0.0.0.0 --port 8000'
    volumes:
      - .:/app
    ports:
      - 8008:8000
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    container_name: dbfinanc-api
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    expose:
      - 5432
    env_file:
      - .env

volumes:
  postgres_data:
