# Copy and paste in a new file inside of k8s/ directory
apiVersion: v1
kind: Secret
metadata:
  name: secret_name
  namespace: your_namespace
type: Opaque
data:
  POSTGRES_DB: encoded_dbname
  POSTGRES_USER: encoded_user
  POSTGRES_PASSWORD: encoded_dbpassword
  POSTGRES_PORT: encoded_dbpassword
  JWT_SECRET_KEY: encoded_dburl
  ALGORITHM: encoded_dburl
