"""create status field and redoing indexes

Revision ID: 3979e92595b0
Revises: 480e3d108c2a
Create Date: 2026-04-21 18:55:17.263875

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3979e92595b0"
down_revision: str | None = "480e3d108c2a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("category_id_created_at_idx", table_name="category")
    op.drop_index("category_id_description_idx", table_name="category")
    op.drop_index("category_id_name_description_created_at_idx", table_name="category")
    op.drop_index("category_id_name_description_created_at_updated_at_idx", table_name="category")
    op.drop_index("category_id_name_description_idx", table_name="category")
    op.drop_index("category_id_name_idx", table_name="category")
    op.drop_index("category_id_updated_at_idx", table_name="category")
    op.drop_index("ix_category_description", table_name="category")
    op.drop_index("ix_category_name", table_name="category")
    op.drop_index("name_description_idx", table_name="category")
    op.create_index("category_lower_name_idx", "category", [sa.text("lower(name)")], unique=False)
    op.add_column(
        "transactions",
        sa.Column("status", sa.String(length=20), nullable=True, default="already_paid"),
    )
    op.drop_index("amount_type_of_transaction_idx", table_name="transactions")
    op.drop_index("desc_amount_idx", table_name="transactions")
    op.drop_index("desc_amount_userid_idx", table_name="transactions")
    op.drop_index(
        "description_amount_type_category_idx",
        table_name="transactions",
        postgresql_where="(category_id IS NOT NULL)",
    )
    op.drop_index("type_of_transaction_date_idx", table_name="transactions")
    op.create_index("transactions_category_id_idx", "transactions", ["category_id"], unique=False)
    op.create_index(
        "transactions_user_id_registration_date_idx",
        "transactions",
        ["user_id", "registration_date"],
        unique=False,
    )
    op.create_index(
        "transactions_user_id_type_registration_date_idx",
        "transactions",
        ["user_id", "type_of_transaction", "registration_date"],
        unique=False,
    )
    op.drop_index("email_created_at_idx", table_name="users")
    op.drop_index("email_pass_idx", table_name="users")
    op.drop_index("email_updated_at_idx", table_name="users")
    op.drop_index("user_created_at_idx", table_name="users")
    op.drop_index("user_email_pass_idx", table_name="users")
    op.drop_index("user_pass_idx", table_name="users")
    op.drop_index("user_updated_at_idx", table_name="users")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("user_updated_at_idx", "users", ["username", "updated_at"], unique=False)
    op.create_index("user_pass_idx", "users", ["username", "password_hash"], unique=False)
    op.create_index(
        "user_email_pass_idx", "users", ["username", "email", "password_hash"], unique=False
    )
    op.create_index("user_created_at_idx", "users", ["username", "created_at"], unique=False)
    op.create_index("email_updated_at_idx", "users", ["email", "updated_at"], unique=False)
    op.create_index("email_pass_idx", "users", ["email", "password_hash"], unique=False)
    op.create_index("email_created_at_idx", "users", ["email", "created_at"], unique=False)
    op.drop_index("transactions_user_id_type_registration_date_idx", table_name="transactions")
    op.drop_index("transactions_user_id_registration_date_idx", table_name="transactions")
    op.drop_index("transactions_category_id_idx", table_name="transactions")
    op.create_index(
        "type_of_transaction_date_idx",
        "transactions",
        ["type_of_transaction", "registration_date"],
        unique=False,
    )
    op.create_index(
        "description_amount_type_category_idx",
        "transactions",
        ["description", "amount", "type_of_transaction", "category_id"],
        unique=False,
        postgresql_where="(category_id IS NOT NULL)",
    )
    op.create_index(
        "desc_amount_userid_idx", "transactions", ["description", "amount", "user_id"], unique=False
    )
    op.create_index("desc_amount_idx", "transactions", ["description", "amount"], unique=False)
    op.create_index(
        "amount_type_of_transaction_idx",
        "transactions",
        ["amount", "type_of_transaction"],
        unique=False,
    )
    op.drop_column("transactions", "status")
    op.drop_index("category_lower_name_idx", table_name="category")
    op.create_index("name_description_idx", "category", ["name", "description"], unique=False)
    op.create_index("ix_category_name", "category", ["name"], unique=False)
    op.create_index("ix_category_description", "category", ["description"], unique=False)
    op.create_index(
        "category_id_updated_at_idx", "category", ["category_id", "updated_at"], unique=False
    )
    op.create_index("category_id_name_idx", "category", ["category_id", "name"], unique=False)
    op.create_index(
        "category_id_name_description_idx",
        "category",
        ["category_id", "name", "description"],
        unique=False,
    )
    op.create_index(
        "category_id_name_description_created_at_updated_at_idx",
        "category",
        ["category_id", "name", "description", "created_at", "updated_at"],
        unique=False,
    )
    op.create_index(
        "category_id_name_description_created_at_idx",
        "category",
        ["category_id", "name", "description", "created_at"],
        unique=False,
    )
    op.create_index(
        "category_id_description_idx", "category", ["category_id", "description"], unique=False
    )
    op.create_index(
        "category_id_created_at_idx", "category", ["category_id", "created_at"], unique=False
    )
    # ### end Alembic commands ###
