"""create category table

Revision ID: b05a5659e069
Revises: 3c76e05b0b4e
Create Date: 2025-02-24 19:05:39.894639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b05a5659e069'
down_revision: Union[str, None] = '3c76e05b0b4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('category_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_index('category_id_created_at_idx', 'category', ['category_id', 'created_at'], unique=False)
    op.create_index('category_id_description_idx', 'category', ['category_id', 'description'], unique=False)
    op.create_index('category_id_name_description_created_at_idx', 'category', ['category_id', 'name', 'description', 'created_at'], unique=False)
    op.create_index('category_id_name_description_created_at_updated_at_idx', 'category', ['category_id', 'name', 'description', 'created_at', 'updated_at'], unique=False)
    op.create_index('category_id_name_description_idx', 'category', ['category_id', 'name', 'description'], unique=False)
    op.create_index('category_id_name_idx', 'category', ['category_id', 'name'], unique=False)
    op.create_index('category_id_updated_at_idx', 'category', ['category_id', 'updated_at'], unique=False)
    op.create_index(op.f('ix_category_description'), 'category', ['description'], unique=False)
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=False)
    op.create_index('name_description_idx', 'category', ['name', 'description'], unique=False)
    op.add_column('transactions', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_index('description_amount_type_category_idx', 'transactions', ['description', 'amount', 'type_of_transaction', 'category_id'], unique=False, postgresql_where=sa.text('category_id IS NOT NULL'))
    op.create_foreign_key(None, 'transactions', 'category', ['category_id'], ['category_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index('description_amount_type_category_idx', table_name='transactions', postgresql_where=sa.text('category_id IS NOT NULL'))
    op.drop_column('transactions', 'category_id')
    op.drop_index('name_description_idx', table_name='category')
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.drop_index(op.f('ix_category_description'), table_name='category')
    op.drop_index('category_id_updated_at_idx', table_name='category')
    op.drop_index('category_id_name_idx', table_name='category')
    op.drop_index('category_id_name_description_idx', table_name='category')
    op.drop_index('category_id_name_description_created_at_updated_at_idx', table_name='category')
    op.drop_index('category_id_name_description_created_at_idx', table_name='category')
    op.drop_index('category_id_description_idx', table_name='category')
    op.drop_index('category_id_created_at_idx', table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
