"""alter status nullable

Revision ID: f4ed6ec7d419
Revises: 3979e92595b0
Create Date: 2026-04-21 19:04:15.676837

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f4ed6ec7d419"
down_revision: str | None = "3979e92595b0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("transactions", "status", existing_type=sa.VARCHAR(length=20), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("transactions", "status", existing_type=sa.VARCHAR(length=20), nullable=True)
    # ### end Alembic commands ###
