apiVersion: apps/v1
kind: Deployment
metadata:
  name: fintracker
  namespace: fintracker-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fintracker
  template:
    metadata:
      labels:
        app: fintracker
    spec:
      containers:
        - name: fintracker-web
          image: jvrochadev/fintracker:1.0.0
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DATABASE_URL
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_DB
