apiVersion: v1
kind: Service
metadata:
  name: fintracker
  namespace: fintracker-dev
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30001
  selector:
    app: fintracker
