kind: ConfigMap
apiVersion: v1
metadata:
  name: fintracker-configmap
  namespace: fintracker-dev
data:
  TOKEN_TYPE: bearer
  ALGORITHM: HS256
  POSTGRES_HOST: "pg-service.databases.svc.cluster.local"
