apiVersion: v1
kind: ConfigMap
metadata:
  name: fintracker-config
  namespace: fintracker-dev
data:
  ALGORITHM: "HS256"
  TOKEN_TYPE: "bearer"
  # Assuming the DB is accessible at this host. If inside k8s, use the service name.
  POSTGRES_HOST: "172.17.0.1" # Use your Host LAN IP or Docker Bridge IP