name: Backend pipeline
run-name: FinancAPI actions
on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      # 1 code checkout
      - name: Checkout code
        uses: actions/checkout@v3

      # 2 configure aws
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-2

      # 3 aws command
      - name: AWS S3 ls
        run: aws s3 ls
